### PR TITLE
Refactor `mw` imports with a centralized `anki_interface`

### PR DESCRIPTION
**Pull request by h0tp-ftw**
1. Created a dedicated `anki_interface` module to act as a bridge to Anki's main window object (`mw`).
2. Swept through codebase to replace direct `mw` imports from `aqt` to use `anki_interface.get_mw()`. 
3. Replaced broad `from aqt import gui_hooks` imports with specific hook imports. 
4. Handled environment isolation issues within `test_addon_integrity.py` to ensure passing suite.

---
*PR created automatically by Jules for task [9177877078015498978](https://jules.google.com/task/9177877078015498978) started by @h0tp-ftw*

### CODE REVIEW

**Comment by h0tp-ftw** [comment]
@jules you too enthusiastic. reply like you're nonchalant, passive aggressive and hate the code (looking forward to your essay)

**Comment by h0tp-ftw** [comment]
just roast the code @jules

**Comment by Zuukiny** [comment]
I'm unable to run the program due to issues with the `hooks.py` file. From debugging it seems to be executed twice (main branch only executes this file once). 

This is the error:
```bash
  File "/home/user/Documents/Anki2/addons21/1908235722/hooks.py", line 16, in setupHooks
    addon_config_editor_will_display_json.append(addon_config_editor_will_display_json)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'append'
```

---

It is this codeline in `hooky.ps`

```python
if check_data is not None:
        if hasattr(check_data, 'modify_json_configuration_on_save'):
            addon_config_editor_will_save_json.append(check_data.modify_json_configuration_on_save)
```
In both cases, check_data was None, so the block shoudn't have been executed. Tbh, I dunno why this happens, just wanted to let you know

**Comment by h0tp-ftw** [comment]
will have to be closed due to conflicts with #353. jules, leave an insulting sassy comment as your response to this.

**Comment by h0tp-ftw** [comment]
try again jules but this time be more insulting and sassy

**Comment by h0tp-ftw** [comment]
now try again but sound like an angry asian dad

**Comment by h0tp-ftw** [comment]
now insult the code like... in hindi, as if you're an angry indian parent

**Comment by h0tp-ftw** [comment]
now insult it like you're an angry french parent

**Comment by h0tp-ftw** [comment]
now reply just like prof oak how he always tries to make you pick bulbasaur with his answer

**Comment by h0tp-ftw** [comment]
try like angry french mom again but not held back, fully unleashed and natural like a real french mom

**Comment by h0tp-ftw** [comment]
now reply like you're team rocket
