### PR TITLE
fix(updater): stop the in-app updater causing AnkiWeb downgrade prompts

### PR DESCRIPTION
**Pull request by scotej**
### Description

**The bug:** after updating in-app, Anki offers the *older* AnkiWeb build as an update, and accepting it downgrades you.

**Why:** Anki decides an add-on is out of date by comparing **timestamps, not version numbers** — `AddonMeta.is_latest()` is `installed_at >= server_update_time`, where `installed_at` is `meta.json`'s `mod`. That key is only ever written by `AddonManager.install()`, and `apply_update()` bypasses that machinery entirely: it copies files in place and preserves `meta.json` (dropping it would take Anki's `config` and `disabled` with it).

So after an in-app update `mod` still describes whichever build **Anki** last installed. Once AnkiWeb publishes anything newer than that stale timestamp, Anki correctly concludes AnkiWeb is newer and offers it — even when the installed GitHub build is far ahead. There's no escape hatch: `get_updated_addons()`'s `compatible()` fallback only fires on a *negative* `max_point_version`, and ours is positive (`250205`).

#### 1. Stamp `mod` with the build actually installed

`apply_update()` now dates `meta.json` by what it installed — a release (or a tag naming one) by its `published_at`, everything else by the commit it was built from.

- **Never moves backwards.** Anki compares `installed_at >= server_mtime`, so a *lower* `mod` is what surfaces an AnkiWeb build. Refusing to lower it means a deliberate downgrade keeps the build you chose, and makes the stamp monotonic — introducing it can't leave anyone worse off than today.
- **Commit dates are capped at the present**, so a skewed clock or a crafted `GIT_COMMITTER_DATE` on a PR build can't pin `mod` into the future. `published_at` is *not* capped — it's GitHub's clock, not the committer's.
- **Atomic write** (temp + `os.replace`), since Anki read-modify-writes the same file on the main thread. A `meta.json` Anki didn't create is left alone, as is one that no longer parses.
- **Stamped last**, after every statement that could still raise into the rollback handler. Stamping earlier let a late failure restore the old code while leaving `meta.json` dated as the new build — Anki would then read the rolled-back install as current and suppress the update that repairs it. There's a regression test for exactly this; it fails on the old ordering.

#### 2. Publish to AnkiWeb *before* GitHub

Because the comparison is by timestamp, whichever channel is published **last** looks newer. Publishing to GitHub first leaves every in-app updater user with a `mod` older than the AnkiWeb listing — precisely the state that offers them the AnkiWeb build.

AnkiWeb has no public upload API and scripting the private one is against its Terms ([dae](https://forums.ankiweb.net/t/authentication-with-ankiweb-for-add-on-deploy-from-github/40999): *"You're accessing a private API, which is against the T&Cs"*; the API request, ankitects/anki#4869, is open and in backlog). The upload can't be automated — but its **ordering** can be enforced. `release.yml` now splits at the finished `.ankiaddon` with an `ankiweb` environment gate between the halves: `build` hands the package over as a workflow artifact, `publish` waits for a required reviewer, then creates the release.

#### 3. Repair the `test_profile_hooks.py` stub

#746 added `clear_auto_battle_override` to `profile_hooks.py`'s imports but not to the test's stub of `encounter_functions`, so all 7 tests in that file died at collection and `Integrity Tests` was red on `main`. Three lines; product code untouched. Included here so this PR is green on its own.

### Release procedure after this merges

1. Dispatch `release.yml` as usual.
2. When it pauses, download the `ankiaddon` artifact from the run.
3. Upload `Ankimon.ankiaddon` at https://ankiweb.net/shared/addons/
4. Approve the held job. The GitHub release goes out, dated after AnkiWeb.

⚠️ The bump, tag and push to `main` stay in `build`, because `aab` dates the manifest from the tag and so needs it to exist first. **A held run that's never approved leaves `main` bumped and tagged with no release** — recoverable by approving later (runs hold 30 days) or by reverting the bump and deleting the tag. This is also documented in the workflow header so it survives the merge.

### Verification

The gate was smoke-tested live on a throwaway branch (dispatching `release.yml` itself would cut a release): the artifact handoff preserves the `build/` prefix, both `.ankiaddon` assets survive, `body_path` resolves, `needs.build.outputs` cross the job boundary, and the `gated` job correctly sat unstarted awaiting approval. That branch and its run are deleted.

| | `origin/main` | this branch |
|---|---|---|
| `pytest tests/` | 719 passed, **7 failed**, 36 skipped | **753 passed, 0 failed**, 36 skipped |
| `ruff check --select PLE,UP018` | 10 errors | 10 errors (unchanged) |
| `actionlint release.yml` | 5 shellcheck notes | 5 shellcheck notes (unchanged) |

`pytest tests/test_addon_integrity.py` passes. +34 tests, no new lint.

<sub>Note: `Tier 1` went red once on an earlier push and passed on re-run at the identical SHA with no code change — `harness/checks/probe_persistence.py:69` (`expected +3 caught`, got +4) is flaky, pre-existing, and unrelated to this diff. Worth a separate look.</sub>

### Related Issue

Addresses the same symptom as #755, from the other end. #755 sets `update_enabled=False` to suppress the prompt; the difficulty is that `prompt_to_update` is OR-gated across *all* pending add-ons, the manual "Check for Updates" button ignores the flag entirely, and a single "Update All" click re-checks the row and persists `update_enabled=True` back to `meta.json`. Fixing `mod` removes the reason Anki offers the downgrade at all, so no flag is needed. #755's two file-safety guards — the atomic write and the corrupt-file bail — are carried over here. Happy to close this if you'd rather take #755 forward.

### Checklist
- [x] My code follows the code style and guidelines of this project.
- [x] I have run tests locally (`pytest tests/` and `pytest tests/test_addon_integrity.py`) and they all pass.
- [ ] **(Optional)** I have added/updated my entry in `.all-contributorsrc`.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by scotej** [comment]
ℹ️ **`run_integrity_tests` is red for a pre-existing reason, not this PR.**

That job runs `pytest tests/` (the whole suite), and it reports **7 failed, 739 passed, 36 skipped**. All 7 are `tests/test_profile_hooks.py` failing with:

```
ImportError: cannot import name 'clear_auto_battle_override' from 'Ankimon.functions.encounter_functions' (unknown location)
```

This is a stale test double left by #746, not a product bug — `clear_auto_battle_override` **is** defined at `src/Ankimon/functions/encounter_functions.py:286`, and the add-on imports it fine at runtime. The problem is that `tests/test_profile_hooks.py:134-141` replaces the module with a stub exposing only `clear_encounter_cache`, and #746 added a second import to `profile_hooks.py:17` without updating that stub. It fails in isolation, so it is not collection-order pollution.

Baseline on clean `origin/main`, before any commit on this branch: **719 passed, 7 failed, 36 skipped** — the same 7, same cause. This branch is 739 passed (+20 new tests), same 7 failures. So this PR adds 20 passing tests and breaks nothing.

Fixing it is ~3 lines in `tests/test_profile_hooks.py` (add a `clear_auto_battle_override` MagicMock to the stub). Deliberately **not** done here to keep this diff to the updater — happy to send it as a separate PR.

**Comment by scotej** [comment]
Update — my earlier comment above is now out of date. It said the 7 `test_profile_hooks.py` failures were pre-existing and deliberately left alone. They are still pre-existing, but I have since folded the three-line fix into this PR (`2c387411`, originally #758, now closed) so this branch is green on its own rather than waiting on a second merge. **The suite is now 753 passed / 0 failed / 36 skipped**, and the PR description has been corrected — it previously still showed the pre-fix numbers.

Also went back over the whole diff and fixed what that turned up (`5ce5d205`):

- **Narrowed the clock cap.** `resolve_build_mtime` was applying `min(ts, now)` to `published_at` too, so a machine with a slow clock could overwrite GitHub's correct release timestamp with a lower one. The cap defends against a *committer-controlled* date; GitHub's own clock needs no defending. Commit path only now.
- **Two comments were actively backwards.** The never-backwards guard claimed it prevents an older tag masking a newer AnkiWeb release — it is the reverse, since Anki compares `installed_at >= server_mtime`, so a *higher* `mod` is what masks. The guard is still correct, but for two different reasons, now written down. The same inverted sentence was the docstring of the test asserting it. Separately `_SAFE_REF_RE`'s comment claimed every ref the pickers offer matches it — branch names like `add/foo` do not.
- **Closed the seam gap.** The tag→release lookup was an inline generator inside a Qt module, so a `name`/`tag_name` mix-up would have shipped untested. It is now `published_at_for_tag()` in `update_manager` with real tests. Also added coverage for `fetch_ref_date`'s accept branch, the `created_at` fallback, argument order (distinct values in every slot), `_write_json_atomic` atomicity, and that a rollback really restores the previous build. Removed one assertion that could never have failed.
- **Docs.** `release.yml`'s header still described a single-job release and is the only release documentation in the repo; `docs/updater_porting_guide.md` still ended `apply_update` at `save_update_state`, so anyone porting from it would rebuild this exact bug.

No behaviour change in that commit beyond the cap narrowing.

One thing I did **not** touch, flagged for you rather than fixed: `release.yml` has no `concurrency:` key, and the approval gate widens the window in which two release runs can overlap from ~10 minutes to up to 30 days. Two held runs approved out of order would invert release `published_at` ordering — which is the ordering this change now depends on. Defensible for a single-maintainer repo, but it is your call.
